---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(rgl)
library(tidyverse)
    knitr::opts_knit$set(root.dir = normalizePath("..")) 
    knitr::knit_hooks$set(webgl = hook_webgl)
```

Try different ways to plot the data

```{r, message=FALSE, error=FALSE, results=FALSE}
# read data
dat1 <- read_csv('data_processed/VMP_gswVariables.csv') %>%
  select(c(profile_nr,Pressure_dbar, Temperature_degC, SP, rho))
head(dat1)
```

Join dat2 table with gps data
```{r message=F}
# read gps info
library(readr)
library(lubridate)
dat_gps1 <- read_csv('data_processed/VMP_profiles_info_GPS_clean.csv') %>%
  mutate(sample_day = factor(day(datetime_start_YMDHMS_UTC), levels=c(29,30,31,1), labels=c('Day1','Day2','Day3','Day4'))) %>%
  select(c('profile_nr', 'sample_day', 'lat', 'long'))
head(dat_gps1)
```

```{r message=FALSE}
# join dat2 and dat_gps2
datj <- inner_join(dat1, dat_gps1, by = 'profile_nr')
head(datj)
```

Plot temperature over longitude per day

```{r, message=FALSE, error=FALSE}
library(shape) # for colour femmecol=jet in matlab
plot2 <- ggplot(data = datj, mapping = aes(x = long, y = Pressure_dbar)) +
  geom_point(mapping = aes(colour = Temperature_degC))
plot2 +
  facet_grid(sample_day ~ .) +
  scale_y_reverse() +
  scale_color_gradientn(colours = femmecol(200), na.value = "transparent")
```

Now defining average Latitude per day to plot per latitude not per day
```{r}
datj_lat <- datj %>%
  group_by(sample_day) %>%
  summarise(lat_av = round(mean(lat),2)) %>%
  inner_join(datj, by = 'sample_day')
head(datj_lat)
```

```{r, message=FALSE, error=FALSE}
library(shape) # for colour femmecol=jet in matlab
plot3 <- ggplot(data = datj_lat, mapping = aes(x = long, y = Pressure_dbar)) +
  geom_point(mapping = aes(colour = Temperature_degC))
plot3 +
  facet_grid(lat_av ~ .) +
  scale_y_reverse() +
  scale_color_gradientn(colours = femmecol(200), na.value = "transparent")
```


